### ISSUE TITLE
A single image or a tiling input?

### ISSUE THREAD

**Issue by KW-NJU** [crp94/textile#1]
Hello! I've just used your **Quick start** code to test our images. Could you please tell me whether it would be better to use a single image or a tiling input as our input image? Looking forward to receiving your reply!

**Comment by crp94** [comment]
Hi!

With the code provided in our Quick start guide, you **do not** have to take care of tiling the input or rescaling it to the appropriate resolution, that is already taken care of by the **Textile** class in textile.py. You can simply provide the path to the input image, and the **Textile** class takes care of rescaling, normalization and tiling, with the configuration specified in the paper. Please refer to the code if you wish to change any of the parameters.

I hope this helped!
